AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ## Whatsapp ##
  LambdaFuncName:
    Type: String
    Default: lambda-whatsapp
  LambdaChatFuncName:
    Type: String
    Default: lambda-Chat
  ApiPathName:
    Type: String
    Default: Whatsapps
  APIName:
    Type: String
    Default: Whatsapps
  WebSocketApiPathName:
    Type: String
    Default: Chat-Wsocket
Resources:
################## Whatsapp ################
  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Timeout: 10
      Code:
        ZipFile: |
          console.log('Loading Whatsapp Lambda function');
      FunctionName:
        Ref: LambdaFuncName
      Handler: index.handler
      Runtime: nodejs16.x
      Role: 
        Fn::ImportValue: PhotoEvent-IAMRoleName
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 9dec56b7-939f-4bc7-9200-47da6127bfe1
  LambdaChatFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Timeout: 10
      Code:
        ZipFile: |
          console.log('Loading Chat Lambda function');
      FunctionName:
        Ref: LambdaChatFuncName
      Handler: index.handler
      Runtime: nodejs16.x
      Role: 
        Fn::ImportValue: PhotoEvent-IAMRoleName
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 9dec56b7-939f-4bc7-9200-47da6127bfe1 
  APIWebSocketWhatsapp:
    Type: 'AWS::ApiGatewayV2::Api'
    Properties:
      Name: 
        Ref: WebSocketApiPathName
      Description: 'Socket para Chat'
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.action
      ApiKeySelectionExpression: $request.header.x-api-key
  WebSocketIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref APIWebSocketWhatsapp
      IntegrationType: AWS_PROXY
      IntegrationUri:  !Sub 
          - >-
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunChatArn}/invocations
          - LambdaFunChatArn: !GetAtt LambdaChatFunction.Arn  
      PayloadFormatVersion: "1.0"
  DefaultRouteSocket:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref APIWebSocketWhatsapp
      RouteKey: $default
      Target: !Sub integrations/${WebSocketIntegration}  
  APIGatewayRestAPI:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name:
        Ref: APIName
      Description: 'Api whatsapp'
      Parameters:
        endpointConfigurationTypes: REGIONAL
      BinaryMediaTypes:
        - image/jpeg
        - multipart/form-data 
  APIGwResorceWhatsapps:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref APIGatewayRestAPI
      ParentId: !GetAtt 
        - APIGatewayRestAPI
        - RootResourceId
      PathPart: 'whatsapp'
  ApiGwWhatsappAny:
    Type: 'AWS::ApiGateway::Method'
    DependsOn:
      - APIGwResorceWhatsapps
      - LambdaFunction
    Properties:
      ResourceId: !Ref APIGwResorceWhatsapps
      HttpMethod: ANY
      AuthorizationType: NONE
      RestApiId: !Ref APIGatewayRestAPI
      RequestParameters:
        method.request.path.proxy: true
      RequestModels :
        application/json:     'Empty'
        multipart/form-data:  'Empty'
        image/jpeg:           'Empty'
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 
          - >-
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFuncWhatsappArn}/invocations
          - LambdaFuncWhatsappArn: !GetAtt LambdaFunction.Arn  
        RequestTemplates:
          application/json: $input.json('$')
          multipart/form-data: $input.json('$')
          image/jpeg: $input.json('$')
        IntegrationResponses:
          - StatusCode: 200
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: $input.json('$')          
            ResponseParameters:
                method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
                method.response.header.Access-Control-Allow-Origin: "'*'"
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: 'Empty'
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true
  ApiGwWhatsappOpt:
    Type: AWS::ApiGateway::Method
    Properties:
      ResourceId: !Ref APIGwResorceWhatsapps
      HttpMethod: OPTIONS
      AuthorizationType: NONE      
      RestApiId: !Ref APIGatewayRestAPI
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS,POST,PUT'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: 'Empty'
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true
    DependsOn:
        - ApiGwWhatsappAny   
  APIGwResorceSessionIdWhatsappsAdd:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref APIGatewayRestAPI
      ParentId: !Ref APIGwResorceWhatsapps
      PathPart: '{fileName}'
    DependsOn:
      - APIGwResorceWhatsapps
  ApiGwWhatsappIDOpt:
    Type: AWS::ApiGateway::Method
    Properties:
      ResourceId: !Ref APIGwResorceSessionIdWhatsappsAdd
      HttpMethod: OPTIONS
      AuthorizationType: NONE      
      RestApiId: !Ref APIGatewayRestAPI
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS,POST,PUT'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: 'Empty'
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true
    DependsOn:
        - APIGwResorceSessionIdWhatsappsAdd   
        - LambdaFunction
  APIGwResorceWhatsappsPerson:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref APIGatewayRestAPI
      ParentId: !Ref APIGwResorceWhatsapps
      PathPart: 'person'
    DependsOn:
      - APIGwResorceWhatsapps
  ApiGwWhatsappPersonAny:
    Type: 'AWS::ApiGateway::Method'
    DependsOn:
      - APIGwResorceWhatsappsPerson
      - LambdaFunction
    Properties:
      RestApiId: !Ref APIGatewayRestAPI
      HttpMethod: ANY
      AuthorizationType: NONE
      ResourceId: !Ref APIGwResorceWhatsappsPerson
      RequestParameters:
        method.request.path.proxy: true
      RequestModels :
        application/json:     'Empty'
        multipart/form-data:  'Empty'
        image/jpeg:           'Empty'
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 
          - >-
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFuncWhatsappArn}/invocations
          - LambdaFuncWhatsappArn: !GetAtt LambdaFunction.Arn  
        RequestTemplates:
          application/json: $input.json('$')
          multipart/form-data: $input.json('$')
          image/jpeg: $input.json('$')
        IntegrationResponses:
          - StatusCode: 200
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: $input.json('$')          
            ResponseParameters:
                method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
                method.response.header.Access-Control-Allow-Origin: "'*'"
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: 'Empty'
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true
  ApiGwWhatsappPersonOpt:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref APIGatewayRestAPI
      HttpMethod: OPTIONS
      AuthorizationType: NONE      
      ResourceId: !Ref APIGwResorceWhatsappsPerson
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS,POST,PUT'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: 'Empty'
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true
    DependsOn:
        - ApiGwWhatsappAny   
  APIGatewayDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      Description : 'Deploy Whatsapps'
      RestApiId: !Ref APIGatewayRestAPI
      StageName: 'dev'
    DependsOn:
      - ApiGwWhatsappAny
      - ApiGwWhatsappPersonAny
  APIGatewayPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt LambdaFunction.Arn
      Principal: apigateway.amazonaws.com
    DependsOn:
      - APIGatewayDeployment
Outputs:
  WebSocketApiUrl:
    Value: !Sub "wss://${APIWebSocketWhatsapp}.execute-api.${AWS::Region}.amazonaws.com/default"